const {gql} = require('apollo-server-express');
const typeDefs = gql`
  # Types 
  scalar FileUpload

  type Message {
    "The ID was generated by NeDB"
    _id: ID!
    name: String!
    date: String!
    message: String!
    file: String
  }
  type File {
    url: String!
  }

  # Queries
  type Query {
      "This will retrieve a list of messages using neDB"
      getAllMessages: [Message]!
  }


  # Mutations 
  type Mutation {
    "This mutation will post a message"
    postMessage(name: String!, message: String!, file: String): Boolean!
    "This mutation will upload a file"
    uploadImage(file: FileUpload!): String!
    "This mutation will delete a post"
    removeMessage(_id: ID!): Boolean!
  }

  #Subscription
  type Subscription {
    "This subscription will watch for postMessage's activities"
    newMessages: [Message!]
  }
`;

module.exports = {typeDefs}


